### ISSUE TITLE
h5p-cli-creator flashcards returns empty cards

### ISSUE THREAD

**Issue by rezeau** [sr258/h5p-cli-creator#1]
Hi Sebastian,
Just tested your h5p-cli-creator to generate H5P flashcards. I do manage to output a correctly formed H5P file, but the contents of my cvs file are not present in the Contents.
Maybe this error can help, when I run your program (on Windows 64 bits) this is what I get:

C:\h5p-cli-creator>node ./dist/index.js flashcards aaa.csv outputfile4.h5p -l=en -n="academicFC"

Creating flashcards content type.
Downloaded content type H5P.Flashcards from H5P hub. (1853874 bytes)
(node:13372) [DEP0005] **DeprecationWarning:** Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Stored H5P package at outputfile4.h5p.

and inside the h5p output file, here is the content, with the empty cards:

{"description":"Flashcards","cards":**[{},{}]**,"showSolutionsRequiresInput":true,"caseSensitive":false,"progressText":"Card @card of @total","next":"Next","previous":"Previous","checkAnswerText":"Check","defaultAnswerText":"Your answer","correctAnswerText":"Correct","incorrectAnswerText":"Incorrect","showSolutionText":"Correct answer","results":"Results","ofCorrect":"@score of @total correct","showResults":"Show results","answerShortText":"A:","retry":"Retry"}

**Comment by sr258** [comment]
Sorry about the super-late reply! I was very busy in July and wanted to answer later, but then forgot about it... 

The warning shouldn't be a problem. I've tried the tool on my machine and it still works fine. Try executing the creator with the demo file that's included in the repository:

``bash
C:\h5p-cli-creator>node ./dist/index.js flashcards ./tests/flash1.csv ./outputfile.h5p -l=en -n="Cards"
``

I'm in the train right now and don't have access to a Windows machine. Maybe that's the issue. I'll try this out at home later (my desktop has a running Windows installation).

**Comment by sr258** [comment]
I've also updated the dependencies in the package. If you re-download everything (```git clone``` or you run ```git fetch``` and run ```git checkout origin/master```) and execute ```npm run build``` again the deprecation warning should not be shown anymore.

**Comment by sr258** [comment]
If it still doesn't work you can also send me your file to serettig@posteo.de if it doesn't contain sensitive user data or is copyright restricted.
