### ISSUE TITLE
Dialog cards, images not showing

### ISSUE THREAD

**Issue by bird2019** [sr258/h5p-cli-creator#2]
I created a dialog cards set, it works if uploaded to a H5P activity except for the impages, although all images exist there.

Besides, if insert the dialog cards h5p file to a book via editor, it does now appear properly, just stucking there.

While the falsh cards work perfectly in both above cases.

**Comment by bird2019** [comment]
as attached
![error](https://user-images.githubusercontent.com/46427226/80028058-d76ee380-84e4-11ea-8464-51e817114d38.JPG)
![images exist](https://user-images.githubusercontent.com/46427226/80028061-d8a01080-84e4-11ea-8569-5a5a81c701e1.JPG)
![no image](https://user-images.githubusercontent.com/46427226/80028062-d938a700-84e4-11ea-8b01-bb85cd8d0d93.JPG)
![stucked](https://user-images.githubusercontent.com/46427226/80028064-d938a700-84e4-11ea-80f0-7b0de5d3c985.JPG)

**Comment by bird2019** [comment]
RESOLVED: after upload one image from the H5P activity program it suddenly shows all the images!

**Comment by sr258** [comment]
Thank you for the report! Fixed in 0.3.
