### ISSUE TITLE
path for images in cli-creator

### ISSUE THREAD

**Issue by villon42** [sr258/h5p-cli-creator#7]
Hello Mr. Rettig, 
first of all thank you very much for creating and providing the cli-creator.
I know you have a lot on your plate and hate to be a nuisance. 
Nevertheless I would like to ask you to show me a way how it would be possible to include the images or audio files that can be used to create dialog.h5p and flash.h5p files via dialog1.csv and flash1.csv, if they can not be found under a url, but locally on your own computer, in my case a Linux system.
With kind regards 
Josef Schippers

**Comment by sr258** [comment]
Hi,

I've updated the application to allow local files. You can see how it works in the `test` directory.

You need to update the files on your machien (`git pull`) and run `npm install` again.

**Comment by villon42** [comment]
Hello Mr. Rettig,

many, many thanks for this prompt and also successful response.

This saves me a lot of work in creating the material for my DAZ students.

With kind regards

Josef Schippers
